# Generated by Django 3.1 on 2024-10-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_email', models.EmailField(max_length=254)),
                ('supplier_phone', models.CharField(blank=True, max_length=15)),
                ('supplier_address', models.TextField(blank=True)),
                ('supplier_country', models.CharField(choices=[('Vietnam', 'Vietnam'), ('China', 'China'), ('Indonesia', 'Indonesia'), ('Thailand', 'Thailand'), ('India', 'India'), ('Philippines', 'Philippines'), ('Pakistan', 'Pakistan'), ('Taiwan', 'Taiwan'), ('Malaysia', 'Malaysia'), ('Bangladesh', 'Bangladesh'), ('Mexico', 'Mexico'), ('Italy', 'Italy'), ('Brazil', 'Brazil'), ('Egypt', 'Egypt'), ('Turkey', 'Turkey'), ('South Korea', 'South Korea'), ('United States', 'United States'), ('Cambodia', 'Cambodia')], max_length=100)),
                ('supplier_is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
