# Generated by Django 3.1 on 2024-10-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20241020_1632'),
        ('suppliers', '0003_auto_20241020_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='store.Product'),
        ),
    ]
