# Generated by Django 5.1.2 on 2024-11-08 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_options_alter_productgallery_options_and_more'),
        ('suppliers', '0006_alter_stockentry_id_alter_supplier_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockentry',
            options={'verbose_name': 'Nhập kho', 'verbose_name_plural': 'Nhập kho'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Nhà cung cấp', 'verbose_name_plural': 'Nhà cung cấp'},
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày nhập'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='quantity',
            field=models.IntegerField(verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier', verbose_name='Nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tổng giá trị'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='store.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_address',
            field=models.TextField(blank=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_country',
            field=models.CharField(choices=[('Vietnam', 'Vietnam'), ('China', 'China'), ('Indonesia', 'Indonesia'), ('Thailand', 'Thailand'), ('India', 'India'), ('Philippines', 'Philippines'), ('Pakistan', 'Pakistan'), ('Taiwan', 'Taiwan'), ('Malaysia', 'Malaysia'), ('Bangladesh', 'Bangladesh'), ('Mexico', 'Mexico'), ('Italy', 'Italy'), ('Brazil', 'Brazil'), ('Egypt', 'Egypt'), ('Turkey', 'Turkey'), ('South Korea', 'South Korea'), ('United States', 'United States'), ('Cambodia', 'Cambodia')], max_length=100, verbose_name='Đất nước'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_email',
            field=models.EmailField(max_length=254, verbose_name='Thư điện tử'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_is_active',
            field=models.BooleanField(default=True, verbose_name='Hoạt động'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(max_length=200, verbose_name='Tên nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật'),
        ),
    ]
