# Generated by Django 5.1.2 on 2024-11-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_stockentry_variation_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='variation_category',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='variation_value',
        ),
        migrations.AddField(
            model_name='stockentry',
            name='color_stockentry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Màu sắc'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='size_stockentry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kích cỡ'),
        ),
    ]
