# Generated by Django 5.1.2 on 2024-11-16 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_product_product_price_and_more'),
        ('suppliers', '0012_remove_stockentry_color_stockentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Tên nguồn sản phẩm'),
        ),
    ]
