# Generated by Django 5.1.2 on 2024-11-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0013_alter_stockentry_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Màu sắc'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kích cỡ'),
        ),
    ]
