# Generated by Django 5.1.2 on 2024-11-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0014_stockentry_color_stockentry_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockentry',
            old_name='size',
            new_name='stock_value',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='color',
        ),
        migrations.AddField(
            model_name='stockentry',
            name='stock_category',
            field=models.CharField(blank=True, choices=[('color', 'Màu sắc'), ('size', 'Kích cỡ')], max_length=100, null=True, verbose_name='Màu sắc'),
        ),
    ]
