# Generated by Django 5.1.2 on 2024-11-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0024_alter_stockentry_total_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_address',
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_city',
            field=models.CharField(blank=True, choices=[('Vietnam', [('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Bình Dương', 'Bình Dương'), ('Đồng Nai', 'Đồng Nai'), ('Tây Ninh', 'Tây Ninh'), ('Đà Nẵng', 'Đà Nẵng'), ('Quảng Nam', 'Quảng Nam')])], max_length=100, null=True, verbose_name='Thành phố'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_country',
            field=models.CharField(choices=[('Vietnam', 'Vietnam')], max_length=100, verbose_name='Đất nước'),
        ),
    ]
