# Generated by Django 5.1.2 on 2024-11-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0026_alter_stockentry_stock_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='stock_category',
            field=models.CharField(blank=True, choices=[('color', 'Màu sắc')], max_length=100, null=True, verbose_name='Danh mục màu sắc'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='stock_value',
            field=models.CharField(blank=True, choices=[('size', 'Kích cỡ')], max_length=100, null=True, verbose_name='Danh mục kích cỡ'),
        ),
    ]
