# Generated by Django 5.1.2 on 2024-12-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0028_stockentry_remaining_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='entry_date',
            field=models.DateTimeField(verbose_name='Ngày nhập'),
        ),
    ]
