# Generated by Django 5.1.2 on 2024-12-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0029_alter_stockentry_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày nhập'),
        ),
    ]
