# Generated by Django 3.1 on 2024-10-03 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_slug', models.SlugField(max_length=200, unique=True)),
                ('product_description', models.TextField(blank=True, max_length=500)),
                ('product_price', models.IntegerField()),
                ('product_images', models.ImageField(upload_to='photos/products')),
                ('product_stock', models.IntegerField()),
                ('product_gender', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kid', 'Kid'), ('unisex', 'Unisex')], default='unisex', max_length=10)),
                ('product_made_in', models.CharField(choices=[('Vietnam', 'Vietnam'), ('China', 'China'), ('Indonesia', 'Indonesia'), ('Thailand', 'Thailand'), ('India', 'India'), ('Philippines', 'Philippines'), ('Pakistan', 'Pakistan'), ('Taiwan', 'Taiwan'), ('Malaysia', 'Malaysia'), ('Bangladesh', 'Bangladesh'), ('Mexico', 'Mexico'), ('Italy', 'Italy'), ('Brazil', 'Brazil'), ('Egypt', 'Egypt'), ('Turkey', 'Turkey'), ('South Korea', 'South Korea'), ('United States', 'United States'), ('Cambodia', 'Cambodia')], default='VN', max_length=100)),
                ('product_is_availabel', models.BooleanField(default=True)),
                ('product_created_date', models.DateTimeField(auto_now_add=True)),
                ('product_modifield_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100)),
                ('variation_value', models.CharField(max_length=100)),
                ('variation_is_active', models.BooleanField(default=True)),
                ('variation_created_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
