# Generated by Django 5.1.2 on 2024-11-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_id_alter_productgallery_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_gender',
            field=models.CharField(choices=[('men', 'Nam'), ('women', 'Nữ'), ('kid', 'Trẻ em'), ('unisex', 'Nam Nữ')], default='Nam Nu', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_made_in',
            field=models.CharField(choices=[('Vietnam', 'Vietnam'), ('China', 'China'), ('Indonesia', 'Indonesia'), ('Thailand', 'Thailand'), ('India', 'India'), ('Philippines', 'Philippines'), ('Pakistan', 'Pakistan'), ('Taiwan', 'Taiwan'), ('Malaysia', 'Malaysia'), ('Bangladesh', 'Bangladesh'), ('Mexico', 'Mexico'), ('Italy', 'Italy'), ('Brazil', 'Brazil'), ('Egypt', 'Egypt'), ('Turkey', 'Turkey'), ('South Korea', 'South Korea'), ('United States', 'United States'), ('Cambodia', 'Cambodia')], default='Vietnam', max_length=100),
        ),
    ]
