# Generated by Django 5.1.2 on 2024-11-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('Màu sắc', 'Màu sắc'), ('Kích cỡ', 'Kích cỡ')], max_length=100),
        ),
    ]
