# Generated by Django 5.1.2 on 2024-11-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'Màu sắc'), ('size', 'Kích cỡ')], max_length=100),
        ),
    ]
