# Generated by Django 5.1.2 on 2024-11-08 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_options'),
        ('store', '0011_alter_variation_variation_category'),
        ('suppliers', '0006_alter_stockentry_id_alter_supplier_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Ảnh phụ sản phẩm', 'verbose_name_plural': 'Ảnh phụ sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'verbose_name': 'Đánh giá', 'verbose_name_plural': 'Đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Biến thể', 'verbose_name_plural': 'Biến thể'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Mô tả sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_gender',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Trẻ em', 'Trẻ em'), ('Nam Nữ', 'Nam Nữ')], default='Nam Nữ', max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=models.ImageField(upload_to='photos/products', verbose_name='Ảnh sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_is_availabel',
            field=models.BooleanField(default=True, verbose_name='Có sẵn'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_made_in',
            field=models.CharField(choices=[('Vietnam', 'Vietnam'), ('China', 'China'), ('Indonesia', 'Indonesia'), ('Thailand', 'Thailand'), ('India', 'India'), ('Philippines', 'Philippines'), ('Pakistan', 'Pakistan'), ('Taiwan', 'Taiwan'), ('Malaysia', 'Malaysia'), ('Bangladesh', 'Bangladesh'), ('Mexico', 'Mexico'), ('Italy', 'Italy'), ('Brazil', 'Brazil'), ('Egypt', 'Egypt'), ('Turkey', 'Turkey'), ('South Korea', 'South Korea'), ('United States', 'United States'), ('Cambodia', 'Cambodia')], default='Vietnam', max_length=100, verbose_name='Nơi sản xuất'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_modifield_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Thời gian sửa đổi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(verbose_name='Gía'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Tên nguồn sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(verbose_name='Tồn kho'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='suppliers.supplier', verbose_name='Nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image_gallery',
            field=models.ImageField(max_length=255, upload_to='store/products', verbose_name='Ảnh phụ sản phẩm'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='review',
            field=models.TextField(blank=True, max_length=500, verbose_name='Đánh giá'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='review_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='review_ip',
            field=models.CharField(blank=True, max_length=20, verbose_name='Giao thức'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='review_rating',
            field=models.FloatField(verbose_name='Điểm đánh giá'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='review_status',
            field=models.BooleanField(default=True, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='review_subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tiêu đề đánh giá'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='review_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'Màu sắc'), ('size', 'Kích cỡ')], max_length=100, verbose_name='Danh mục biến thể'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_is_active',
            field=models.BooleanField(default=True, verbose_name='Hoạt động'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(max_length=100, verbose_name='Gía trị'),
        ),
    ]
