# Generated by Django 5.1.2 on 2024-11-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_variation_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/variations/', verbose_name='Hình ảnh biến thể'),
        ),
    ]
