# Generated by Django 5.1.2 on 2024-11-15 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_variation_variation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='variation_image',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='variation_stock',
        ),
        migrations.AlterField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Sản phẩm'),
        ),
    ]
