# Generated by Django 5.1.2 on 2024-11-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_variation_variation_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default='0', verbose_name='Gía'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(default='0', verbose_name='Tồn kho'),
        ),
    ]
