# Generated by Django 5.1.2 on 2024-11-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_variation_variation_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='variation_stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(verbose_name='Gía'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(verbose_name='Tồn kho'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'Màu sắc'), ('size', 'Kích cỡ')], max_length=100, verbose_name='Danh mục biến thể'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(max_length=100, verbose_name='Gía trị'),
        ),
    ]
