# Generated by Django 5.1.2 on 2024-11-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_variation_variation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0, verbose_name='Gía'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(default=0, verbose_name='Tồn kho'),
        ),
    ]
