# Generated by Django 5.1.2 on 2024-11-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_variation_variation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'Màu sắc'), ('size', 'Kích cỡ')], max_length=100, verbose_name='Danh mục biến thể'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(max_length=100, verbose_name='Gía trị'),
        ),
    ]
