# Generated by Django 5.1.2 on 2024-11-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_variation_variation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Màu sắc'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kích cỡ'),
        ),
    ]
