# Generated by Django 5.1.2 on 2024-11-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_variation_variation_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='stock',
        ),
    ]
