# Generated by Django 5.1.2 on 2024-11-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_remove_variation_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Tồn kho'),
        ),
    ]
