# Generated by Django 5.1.2 on 2024-11-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_variation_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='variation_image',
        ),
    ]
