# Generated by Django 5.1.2 on 2024-11-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_remove_variation_variation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Màu sắc'),
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kích cỡ'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(blank=True, choices=[('color', 'Màu sắc')], max_length=100, null=True, verbose_name='Danh mục màu sắc'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(blank=True, choices=[('size', 'Kích cỡ')], max_length=100, null=True, verbose_name='Danh mục kích cỡ'),
        ),
    ]
