# Generated by Django 5.1.2 on 2024-11-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_variation_variation_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='variation_unit_price',
        ),
    ]
