# Generated by Django 3.1 on 2024-10-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(choices=[('United States', 'United States'), ('Canada', 'Canada'), ('Mexico', 'Mexico'), ('United Kingdom', 'United Kingdom'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Spain', 'Spain'), ('Netherlands', 'Netherlands'), ('Belgium', 'Belgium'), ('Austria', 'Austria'), ('Switzerland', 'Switzerland'), ('Sweden', 'Sweden'), ('Denmark', 'Denmark'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('Ireland', 'Ireland'), ('Portugal', 'Portugal'), ('Greece', 'Greece'), ('Poland', 'Poland'), ('Czech Republic', 'Czech Republic'), ('Hungary', 'Hungary'), ('Romania', 'Romania'), ('Russia', 'Russia'), ('Australia', 'Australia'), ('New Zealand', 'New Zealand'), ('Japan', 'Japan'), ('South Korea', 'South Korea'), ('China', 'China'), ('Hong Kong', 'Hong Kong'), ('Taiwan', 'Taiwan'), ('Singapore', 'Singapore'), ('Malaysia', 'Malaysia'), ('Thailand', 'Thailand'), ('Indonesia', 'Indonesia'), ('Philippines', 'Philippines'), ('Vietnam', 'Vietnam'), ('India', 'India'), ('United Arab Emirates', 'United Arab Emirates'), ('Saudi Arabia', 'Saudi Arabia'), ('Turkey', 'Turkey'), ('South Africa', 'South Africa'), ('Brazil', 'Brazil'), ('Argentina', 'Argentina'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Peru', 'Peru'), ('Israel', 'Israel'), ('Egypt', 'Egypt')], max_length=50)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('village', models.CharField(blank=True, max_length=50, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
