# Generated by Django 3.1 on 2024-10-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20241015_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
