# Generated by Django 3.1 on 2024-10-07 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20241003_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile_address', models.CharField(blank=True, max_length=100)),
                ('user_profile_picture', models.ImageField(blank=True, upload_to='userprofile')),
                ('user_profile_country', models.CharField(blank=True, max_length=20)),
                ('user_profile_city', models.CharField(blank=True, max_length=20)),
                ('user_profile_village', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
