# Generated by Django 3.1 on 2024-10-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_account_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_city',
        ),
    ]
