# Generated by Django 3.1 on 2024-10-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_account_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
