# Generated by Django 3.1 on 2024-10-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='state',
        ),
        migrations.AddField(
            model_name='account',
            name='state_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
