# Generated by Django 3.1 on 2024-10-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20241015_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_address',
        ),
    ]
