# Generated by Django 5.1.2 on 2024-11-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_city_alter_account_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Nhóm quản lý tài khoản', 'verbose_name_plural': 'Tài khoản người dùng'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Nhóm quản lý tài khoản', 'verbose_name_plural': 'Hồ sơ người dùng'},
        ),
    ]
