# Generated by Django 5.1.2 on 2024-11-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_account_options_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Tài khoản người dùng', 'verbose_name_plural': 'Tài khoản người dùng'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Hồ sơ người dùng', 'verbose_name_plural': 'Hồ sơ người dùng'},
        ),
    ]
