# Generated by Django 5.1.2 on 2024-11-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_account_options_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='userprofile', verbose_name='Ảnh tài khoản'),
        ),
    ]
