# Generated by Django 5.1.2 on 2024-12-04 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_account_mbs_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discoundmbslevel',
            options={'verbose_name': 'Mã giảm giá hạng thành viên', 'verbose_name_plural': 'Mã giảm giá hạng thành viên'},
        ),
    ]
