# Generated by Django 5.1.2 on 2024-12-04 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_discoundmbslevel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='mbs_level',
        ),
        migrations.DeleteModel(
            name='DiscoundMBSLevel',
        ),
    ]
