# Generated by Django 5.1.2 on 2024-11-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục sản phẩm'},
        ),
    ]
