# Generated by Django 5.1.2 on 2024-11-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_images',
            field=models.ImageField(blank=True, upload_to='photos/categories', verbose_name='Ảnh danh mục'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tên danh mục'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Tên nguồn danh mục'),
        ),
    ]
