# Generated by Django 5.1.2 on 2024-11-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsChartPlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Biểu đồ thống kê',
                'verbose_name_plural': 'Biểu đồ thống kê',
            },
        ),
    ]
