# Generated by Django 3.1 on 2024-10-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20241004_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_is_ordered',
            field=models.BooleanField(max_length=20),
        ),
    ]
