# Generated by Django 3.1 on 2024-10-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20241005_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
