# Generated by Django 3.1 on 2024-10-06 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20241005_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order_product_color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order_product_size',
        ),
    ]
