# Generated by Django 5.1.2 on 2024-11-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20241006_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Packing', 'Packing'), ('Waiting for Pickup', 'Waiting for Pickup'), ('In Transit', 'In Transit'), ('At Distribution Center', 'At Distribution Center'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Delivery Failed', 'Delivery Failed')], default='Processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
