# Generated by Django 5.1.2 on 2024-11-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_id_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Đang xử lý', 'Đang xử lý'), ('Đóng gói', 'Đóng gói'), ('Chờ Nhận Hàng', 'Chờ Nhận Hàng'), ('Đang vận chuyển', 'Đang vận chuyển'), ('Tại Trung tâm Phân phối', 'Tại Trung tâm Phân phối'), ('Ra đi để giao hàng', 'Ra đi để giao hàng'), ('Đã giao', 'Đã giao'), ('Giao hàng không thành công', 'Giao hàng không thành công')], default='Đang xử lý', max_length=100),
        ),
    ]
