# Generated by Django 5.1.2 on 2024-11-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_phone',
            field=models.CharField(max_length=50),
        ),
    ]
