# Generated by Django 5.1.2 on 2024-11-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_options_alter_orderproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_country',
            field=models.CharField(choices=[('Vietnam', 'Vietnam')], max_length=50, null=True, verbose_name='Đất nước'),
        ),
    ]
