# Generated by Django 5.1.2 on 2024-11-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_order_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_tax',
            field=models.IntegerField(verbose_name='Phí giao hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(verbose_name='Tổng'),
        ),
    ]
