# Generated by Django 5.1.2 on 2024-12-06 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_payment_alter_orderproduct_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_reason', models.TextField(max_length=255, verbose_name='Lý do trả hàng')),
                ('status', models.CharField(choices=[('Đang xử lý', 'Đang xử lý'), ('Đã chấp nhận', 'Đã chấp nhận'), ('Đã từ chối', 'Đã từ chối'), ('Hoàn thành', 'Hoàn thành')], default='Đang xử lý', max_length=50, verbose_name='Trạng thái')),
                ('return_image', models.ImageField(blank=True, null=True, upload_to='return_images/', verbose_name='Ảnh minh họa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày yêu cầu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Yêu cầu trả hàng',
                'verbose_name_plural': 'Yêu cầu trả hàng',
            },
        ),
    ]
