# Generated by Django 5.1.2 on 2024-12-06 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_returnrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='return_image',
        ),
        migrations.CreateModel(
            name='ReturnRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='return_request_images/', verbose_name='Ảnh minh họa')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.returnrequest', verbose_name='Yêu cầu trả hàng')),
            ],
        ),
    ]
