# Generated by Django 5.1.2 on 2024-12-06 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_returnrequest_return_image_returnrequestimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnrequestimage',
            options={'verbose_name': 'Ảnh minh họa', 'verbose_name_plural': 'Ảnh minh họa'},
        ),
    ]
