# Generated by Django 5.1.2 on 2024-12-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_returnrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('Đang xử lý', 'Đang xử lý'), ('Đã chấp nhận', 'Đã chấp nhận'), ('Đã từ chối', 'Đã từ chối'), ('Hoàn thành', 'Hoàn thành')], default='Đang xử lý', max_length=50, verbose_name='Trạng thái'),
        ),
    ]
